# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "pypy"

# Enable Python 3.7. Requires OpenSSL 1.0.2+ which is not available for Trusty
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true

before_install:
    - "wget https://s3.amazonaws.com/textblob/nltk_data.tar.gz"
    - "tar -xzvf nltk_data.tar.gz -C ~"

install:
  - pip install -r requirements-tests.txt
  - pip install -U .

script: python run_tests.py
